import { useState, useMemo, useEffect } from "react";
import {
  FaEye,
  FaTrash,
  FaPrint,
  FaMoneyBillWave,
  FaFilePdf,
} from "react-icons/fa";

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import Pagination from "../common/Pagination";

export default function BillTable({
  bills,
  onPay,
  onView,
  onDelete
}) {
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(25);

  useEffect(() => {
    setPage(1);
  }, [bills.length]);

  const pagedBills = useMemo(() => {
    if (pageSize === "all" || pageSize === "All" || Number(pageSize) >= bills.length) {
      return bills;
    }
    const numericSize = Number(pageSize) || 25;
    const start = (page - 1) * numericSize;
    return bills.slice(start, start + numericSize);
  }, [bills, page, pageSize]);

  function downloadBillPDF(bill) {
    const doc = new jsPDF();
    const status = bill.displayStatus || bill.status;

    doc.setFontSize(20);
    doc.text("Smart Manager", 105, 18, { align: "center" });

    doc.setFontSize(12);
    doc.text("Garbage Collection Bill", 105, 28, { align: "center" });

    autoTable(doc, {
      startY: 40,
      theme: "grid",
      head: [["Field", "Details"]],
      body: [
        ["Flat", bill.flat],
        ["Resident", bill.residentName],
        ["Block", bill.block || "-"],
        ["Bill Amount", `₹${Number(bill.amount).toLocaleString()}`],
        ["Month", `${bill.month} ${bill.year}`],
        ["Due Date", bill.dueDate || "-"],
        ["Status", status],
        ["Payment Date", bill.paymentDate || "-"],
        ["Payment Method", bill.paymentMethod || "-"],
        ["Receipt ID", bill.paymentId || "-"],
      ],
    });

    doc.save(`Bill-${bill.flat}-${bill.month}-${bill.year}.pdf`);
  }

  function printBill(bill) {
    const status = bill.displayStatus || bill.status;
    const printWindow = window.open("", "_blank");

    printWindow.document.write(`
      <html>
      <head>
        <title>Bill - ${bill.flat}</title>
        <style>
          body { font-family: Arial, sans-serif; padding: 30px; }
          h2 { text-align: center; margin-bottom: 5px; }
          h4 { text-align: center; color: #666; margin-top: 0; }
          table { width: 100%; border-collapse: collapse; margin-top: 20px; }
          td { border: 1px solid #ddd; padding: 10px; }
          td:first-child { font-weight: bold; width: 40%; background: #f9f9f9; }
          .footer { margin-top: 40px; text-align: center; color: #999; font-size: 12px; }
        </style>
      </head>
      <body>
        <h2>Smart Manager</h2>
        <h4>Garbage Collection Bill</h4>
        <table>
          <tr><td>Flat</td><td>${bill.flat}</td></tr>
          <tr><td>Resident</td><td>${bill.residentName}</td></tr>
          <tr><td>Block</td><td>${bill.block || "-"}</td></tr>
          <tr><td>Amount</td><td>₹${Number(bill.amount).toLocaleString()}</td></tr>
          <tr><td>Billing Period</td><td>${bill.month} ${bill.year}</td></tr>
          <tr><td>Due Date</td><td>${bill.dueDate || "-"}</td></tr>
          <tr><td>Status</td><td>${status}</td></tr>
          <tr><td>Payment Date</td><td>${bill.paymentDate || "-"}</td></tr>
          <tr><td>Method</td><td>${bill.paymentMethod || "-"}</td></tr>
          <tr><td>Receipt ID</td><td>${bill.paymentId || "-"}</td></tr>
        </table>
        <div class="footer">Generated by Smart Manager</div>
      </body>
      </html>
    `);

    printWindow.document.close();
    printWindow.print();
  }

  return (
    <div className="bg-white rounded-2xl shadow-sm overflow-x-auto border border-gray-100">
      <table className="w-full">
        <thead className="bg-gray-50 border-b border-gray-100">
          <tr>
            <th className="p-4 text-left font-bold text-gray-600">Flat</th>
            <th className="p-4 text-left font-bold text-gray-600">Resident</th>
            <th className="p-4 text-left font-bold text-gray-600">Amount</th>
            <th className="p-4 text-left font-bold text-gray-600">Status</th>
            <th className="p-4 text-left font-bold text-gray-600">Due Date</th>
            <th className="p-4 text-center font-bold text-gray-600">Actions</th>
          </tr>
        </thead>
        <tbody>
          {bills.length === 0 ? (
            <tr>
              <td colSpan="6" className="text-center py-16 text-gray-500">
                <div className="flex flex-col items-center gap-3">
                  <FaFilePdf className="text-5xl text-gray-300" />
                  <p className="text-lg font-medium">No Bills Found</p>
                </div>
              </td>
            </tr>
          ) : (
            pagedBills.map((bill) => {
              const status = bill.displayStatus || bill.status;
              const isSettled = status === "Paid" || status === "Exempted";
              
              return (
                <tr key={bill.id} className="border-t border-gray-50 hover:bg-emerald-50/30 transition">
                  <td className="p-4 font-bold text-gray-800">{bill.flat}</td>
                  <td className="p-4 font-medium text-gray-600">{bill.residentName}</td>
                  <td className="p-4 font-bold text-emerald-600">₹{bill.amount}</td>
                  <td className="p-4">
                    <span className={`px-3 py-1.5 rounded-full text-xs font-bold tracking-wide uppercase ${
                        status === "Paid" ? "bg-green-100 text-green-700"
                        : status === "Pending" ? "bg-yellow-100 text-yellow-700"
                        : status === "Exempted" ? "bg-gray-200 text-gray-700"
                        : status === "Overdue" ? "bg-red-100 text-red-700"
                        : "bg-red-100 text-red-700"
                      }`}
                    >
                      {status}
                    </span>
                  </td>
                  <td className="p-4 font-medium text-gray-500">{bill.dueDate || "-"}</td>
                  <td className="p-4">
                    <div className="flex justify-center gap-2">
                      {/* Collect */}
                      <button
                        onClick={() => onPay(bill)}
                        disabled={isSettled}
                        className={`p-2.5 rounded-lg transition shadow-sm ${
                          isSettled 
                            ? "bg-gray-100 text-gray-400 cursor-not-allowed" 
                            : "bg-emerald-100 hover:bg-emerald-600 text-emerald-600 hover:text-white"
                        }`}
                        title={isSettled ? "Payment Settled" : "Collect Payment"}
                      >
                        <FaMoneyBillWave />
                      </button>

                      {/* View */}
                      <button 
                        onClick={() => onView(bill)}
                        className="bg-blue-50 hover:bg-blue-600 text-blue-600 hover:text-white p-2.5 rounded-lg transition shadow-sm" 
                        title="View Bill"
                      >
                        <FaEye />
                      </button>

                      {/* PDF Download */}
                      <button
                        onClick={() => downloadBillPDF(bill)}
                        className="bg-red-50 hover:bg-red-600 text-red-600 hover:text-white p-2.5 rounded-lg transition shadow-sm"
                        title="Download PDF"
                      >
                        <FaFilePdf />
                      </button>
                      
                      {/* Print */}
                      <button
                        onClick={() => printBill(bill)}
                        className="bg-indigo-50 hover:bg-indigo-600 text-indigo-600 hover:text-white p-2.5 rounded-lg transition shadow-sm"
                        title="Print Bill"
                      >
                        <FaPrint />
                      </button>
                      
                      {/* Delete */}
                      <button 
                        onClick={() => onDelete(bill)}
                        className="bg-gray-50 hover:bg-red-600 text-gray-600 hover:text-white p-2.5 rounded-lg transition shadow-sm" 
                        title="Delete Bill"
                      >
                        <FaTrash />
                      </button>
                    </div>
                  </td>
                </tr>
              );
            })
          )}
        </tbody>
      </table>

      {bills.length > 0 && (
        <Pagination
          currentPage={page}
          totalItems={bills.length}
          pageSize={pageSize}
          onPageChange={setPage}
          onPageSizeChange={setPageSize}
          pageSizeOptions={[25, 50, 100, "all"]}
        />
      )}
    </div>
  );
}